# E-Commerce Profitability Analysis

### 1. Import Data and Explore

In [1]:
import pandas as pd
import numpy as np

#### 1.1 Load all three CSV

In [2]:
orders = pd.read_csv(r'D:\Data Analysis\1.Projects\6.E-Commerce Profitability Analysis\resources\orders.csv')

In [ ]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          2000 non-null   object
 1   customer_id       2000 non-null   object
 2   order_date        2000 non-null   object
 3   channel           2000 non-null   object
 4   payment_method    2000 non-null   object
 5   region            2000 non-null   object
 6   items_ordered     2000 non-null   int64
 7   primary_category  2000 non-null   object
 8   gross_revenue     2000 non-null   float64
 9   discount_pct      2000 non-null   int64
 10  discount_amount   2000 non-null   float64
 11  shipping_cost     2000 non-null   float64
 12  product_cost      2000 non-null   float64
 13  platform_fee      2000 non-null   float64
 14  transaction_fee   2000 non-null   float64
 15  returned          2000 non-null   object
 16  refund_amount     2000 non-null   float64
 17  net_revenue       2000 non-null   float64
 18  total_costs       2000 non-null   float64
 19  profit            2000 non-null   float64
dtypes: float64(10), int64(2), object(8)
memory usage: 312.6+ KB

In [7]:
marketing_spend = pd.read_csv(r'D:\Data Analysis\1.Projects\6.E-Commerce Profitability Analysis\resources\marketing_spend.csv')

In [11]:
marketing_spend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   month               144 non-null    object
 1   platform            144 non-null    object
 2   spend               144 non-null    float64
 3   impressions         144 non-null    int64
 4   clicks              144 non-null    int64
 5   conversions         144 non-null    int64
 6   revenue_attributed  144 non-null    float64
 7   cpc                 144 non-null    float64
 8   cpa                 144 non-null    float64
 9   roas                144 non-null    float64
dtypes: float64(5), int64(3), object(2)
memory usage: 11.4+ KB

In [5]:
products = pd.read_csv(r'D:\Data Analysis\1.Projects\6.E-Commerce Profitability Analysis\resources\products.csv')

In [6]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              207 non-null    object
 1   product_name            207 non-null    object
 2   category                207 non-null    object
 3   sub_category            207 non-null    object
 4   unit_cost               207 non-null    float64
 5   selling_price           207 non-null    float64
 6   shipping_cost_per_unit  207 non-null    float64
 7   weight_lbs              207 non-null    float64
 8   supplier                207 non-null    object
dtypes: float64(4), object(5)
memory usage: 14.7+ KB

In [8]:
pd.set_option('display.max.rows', 200)
pd.set_option('display.max.columns', 30)

#### 1.2 Verify the Correctness of Total Costs

In [6]:
orders['costs_verify'] = round(orders['product_cost'] + orders['platform_fee'] + orders['transaction_fee'] + orders['shipping_cost'] - orders['total_costs'],2)
orders[orders['costs_verify'] != 0][['order_id','costs_verify']]

Empty DataFrame
Columns: [order_id, costs_verify]
Index: []

In [5]:
orders['profit_verify'] = (orders['net_revenue'] - orders['total_costs'] - orders['profit']).round(2)
orders[orders['profit_verify'] != 0][['order_id','profit_verify']]

Empty DataFrame
Columns: [order_id, profit_verify]
Index: []

In [ ]:
# All the total costs are caculated correctly

### 2.Category Profitability
2.1 Group orders by product category.

2.2 Calculate total revenue, total costs, total profit, and profit margin for each.

2.3  Which categories are the most and least profitable, and what is driving the difference (product cost, shipping, returns, or discounts)?

2.4 Identify the top and bottom performers.

In [18]:
orders_by_category = orders.groupby('primary_category')['order_id'].count().reset_index(name = 'number_of_orders')
orders_by_category.sort_values('number_of_orders',ascending = False,inplace=True)

In [19]:
orders_by_category

  primary_category  number_of_orders
2         Clothing               293
6           Sports               292
3      Electronics               267
7             Toys               257
4  Food & Beverage               247
1            Books               239
0           Beauty               205
5   Home & Kitchen               200

In [ ]:
category_profit = orders.groupby('primary_category').agg(total_revenue = ('net_revenue','sum'),
                                                                          total_costs = ('total_costs','sum')).reset_index()
category_profit['total_profit'] = category_profit['total_revenue'] - category_profit['total_costs']
category_profit['margin_profit'] = round(category_profit['total_profit'] / category_profit['total_revenue'] * 100,2)

In [11]:
category_profit.sort_values('margin_profit',ascending = False, inplace = True)
category_profit

  primary_category  total_revenue  total_costs  total_profit  margin_profit
3      Electronics       44885.84     30912.38      13973.46          31.13
7             Toys       33595.68     24809.43       8786.25          26.15
5   Home & Kitchen       26359.76     19671.19       6688.57          25.37
4  Food & Beverage       30662.69     23070.92       7591.77          24.76
6           Sports       32329.83     24733.20       7596.63          23.50
2         Clothing       31383.13     25110.65       6272.48          19.99
0           Beauty       18254.07     15079.19       3174.88          17.39
1            Books       18847.37     16597.58       2249.79          11.94

In [9]:
orders.head()

,order_id,customer_id,order_date,channel,payment_method,region,items_ordered,primary_category,gross_revenue,discount_pct,discount_amount,shipping_cost,product_cost,platform_fee,transaction_fee,returned,refund_amount,net_revenue,total_costs,profit,Unnamed: 20
0,ORD-000001,C-0617,2025/6/24,Mobile App,Gift Card,Northeast,2,Electronics,261.39,0,0.00,22.28,92.30,0.00,7.88,No,0.0,261.39,122.46,138.93,0
1,ORD-000002,C-0720,2025/8/23,Website,Credit Card,Midwest,1,Beauty,24.02,0,0.00,3.98,10.75,0.00,1.00,No,0.0,24.02,15.73,8.29,0
2,ORD-000003,C-0189,2025/7/20,Website,Credit Card,Southeast,2,Toys,52.60,0,0.00,14.60,31.41,0.00,1.83,No,0.0,52.60,47.84,4.76,0
3,ORD-000004,C-0058,2025/7/17,Mobile App,Debit Card,Southeast,2,Sports,30.63,5,1.53,30.98,16.27,0.00,1.14,No,0.0,29.10,48.39,-19.29,0
4,ORD-000005,C-0580,2025/10/11,Marketplace,Credit Card,Northeast,1,Sports,11.99,25,3.00,10.30,6.88,1.35,0.56,No,0.0,8.99,19.09,-10.10,0

In [ ]:
# The highest profitable category is Electronics, and the lowest is Books

In [38]:
category_cost = orders.groupby('primary_category').agg(product_cost =('product_cost','sum'),
                                               platform_fee = ('platform_fee','sum'),
                                               transaction_fee = ('transaction_fee','sum'),
                                               shipping_cost = ('shipping_cost','sum'),
                                               total_revenue = ('net_revenue','sum'),
                                               total_cost = ('total_costs','sum')).reset_index()

In [16]:
category_cost

,primary_category,product_cost,platform_fee,transaction_fee,shipping_cost,total_cost
0,Beauty,8590.59,699.66,615.96,5172.98,15079.19
1,Books,8956.87,698.58,679.33,6262.80,16597.58
2,Clothing,15345.43,1229.47,1091.15,7444.60,25110.65
3,Electronics,20091.06,2181.45,1500.07,7139.80,30912.38
4,Food & Beverage,14299.07,1265.14,1064.95,6441.76,23070.92
5,Home & Kitchen,12348.67,1441.41,892.27,4988.84,19671.19
6,Sports,15691.62,1043.51,1083.35,6914.72,24733.20
7,Toys,15610.64,1335.40,1123.03,6740.36,24809.43

In [43]:
cost_list = category_cost.columns.tolist()[1:-2]

In [44]:
cost_list

['product_cost', 'platform_fee', 'transaction_fee', 'shipping_cost']

In [ ]:
# Analyzing the cost structure of each category by calculating the proportion of each cost component to the total revenue for each category. 
# This will help identify which cost components are the most significant contributors to the total costs
for cost in cost_list :
    category_cost[cost + '_proportion'] = (category_cost[cost] / category_cost['total_revenue'] * 100 ).round(2)

In [57]:
cost_proportion = category_cost.iloc[:, [0,7,8,9,10]]

In [ ]:
cost_analysis = category_profit[['primary_category','margin_profit']].merge(cost_proportion,on ='primary_category')
cost_analysis

,primary_category,margin_profit,product_cost_proportion,platform_fee_proportion,transaction_fee_proportion,shipping_cost_proportion
0,Electronics,31.13,44.76,4.86,3.34,15.91
1,Toys,26.15,46.47,3.97,3.34,20.06
2,Home & Kitchen,25.37,46.85,5.47,3.38,18.93
3,Food & Beverage,24.76,46.63,4.13,3.47,21.01
4,Sports,23.50,48.54,3.23,3.35,21.39
5,Clothing,19.99,48.90,3.92,3.48,23.72
6,Beauty,17.39,47.06,3.83,3.37,28.34
7,Books,11.94,47.52,3.71,3.60,33.23

In [ ]:
#  The product categories with lower profitability(e.g.Beauty, Books) have higher shipping cost, shipping cost is significant matter to the profitability

### 3. Channel Analysis
3.1 Group by sales channel

3.2 Compare average order value, average profit, and return rate across channels.

3.3 Factor in platform fees for Marketplace and Social Commerce.

In [ ]:
# Average Order Value = Total Revenue / Number of Orders
# Return Rate = Number of Return

In [8]:
orders.head(5)

,order_id,customer_id,order_date,channel,payment_method,region,items_ordered,primary_category,gross_revenue,discount_pct,discount_amount,shipping_cost,product_cost,platform_fee,transaction_fee,returned,refund_amount,net_revenue,total_costs,profit,Unnamed: 20
0,ORD-000001,C-0617,2025/6/24,Mobile App,Gift Card,Northeast,2,Electronics,261.39,0,0.00,22.28,92.30,0.00,7.88,No,0.0,261.39,122.46,138.93,0
1,ORD-000002,C-0720,2025/8/23,Website,Credit Card,Midwest,1,Beauty,24.02,0,0.00,3.98,10.75,0.00,1.00,No,0.0,24.02,15.73,8.29,0
2,ORD-000003,C-0189,2025/7/20,Website,Credit Card,Southeast,2,Toys,52.60,0,0.00,14.60,31.41,0.00,1.83,No,0.0,52.60,47.84,4.76,0
3,ORD-000004,C-0058,2025/7/17,Mobile App,Debit Card,Southeast,2,Sports,30.63,5,1.53,30.98,16.27,0.00,1.14,No,0.0,29.10,48.39,-19.29,0
4,ORD-000005,C-0580,2025/10/11,Marketplace,Credit Card,Northeast,1,Sports,11.99,25,3.00,10.30,6.88,1.35,0.56,No,0.0,8.99,19.09,-10.10,0

In [40]:
set(orders['returned'])

{'No', 'Yes'}

In [47]:
channel_aggregation = orders.groupby('channel').agg(average_of_value = pd.NamedAgg(column = 'net_revenue',aggfunc='mean'),
                                                    average_profit = pd.NamedAgg(column ='profit',aggfunc='mean'),
                                                    number_orders = pd.NamedAgg(column ='order_id',aggfunc='count'),
                                                    number_returns = pd.NamedAgg(column = 'returned', aggfunc= lambda x: (x == "Yes").sum())).reset_index()
channel_aggregation['return_rate'] = channel_aggregation['number_returns'] / channel_aggregation['number_orders'] * 100
channel_aggregation = channel_aggregation.round(2)

In [48]:
channel_aggregation.sort_values('average_profit', ascending= False, inplace=True)

In [49]:
channel_aggregation

,channel,average_of_value,average_profit,number_orders,number_returns,return_rate
1,Mobile App,122.06,36.32,589,43,7.30
3,Website,116.97,31.60,795,56,7.04
2,Social Commerce,111.32,17.11,197,18,9.14
0,Marketplace,118.15,15.40,419,27,6.44

### 4. Marketing ROI
4.1 Analyze the marketing spend dataset.

4.2 Calculate ROAS, cost per acquisition, and cost per click by platform.

4.3 Identify which platforms are underperforming.

In [8]:
marketing_spend

,month,platform,spend,impressions,clicks,conversions,revenue_attributed,cpc,cpa,roas
0,2024-01,Google Ads,2676.14,303594,13271,500,43063.16,0.20,5.35,16.09
1,2024-01,Facebook Ads,1971.43,338022,7163,333,15950.86,0.28,5.92,8.09
2,2024-01,Instagram Ads,2418.95,561361,18729,748,54454.46,0.13,3.23,22.51
3,2024-01,TikTok Ads,1141.70,554273,6967,346,22369.23,0.16,3.30,19.59
4,2024-01,Email Marketing,868.82,29509,1215,58,4223.97,0.72,14.98,4.86
...,...,...,...,...,...,...,...,...,...,...
139,2025-12,Facebook Ads,7480.08,1454093,34543,2668,201086.58,0.22,2.80,26.88
140,2025-12,Instagram Ads,5671.66,910841,21625,869,91175.48,0.26,6.53,16.08
141,2025-12,TikTok Ads,3408.50,755034,18046,1171,111842.60,0.19,2.91,32.81
142,2025-12,Email Marketing,1796.66,15675,477,11,1198.99,3.77,163.33,0.67
143,2025-12,Influencer,6329.25,337538,17751,1374,103555.05,0.36,4.61,16.36

In [ ]:
# Verify the correctness of ROAS
((marketing_spend['revenue_attributed'] / marketing_spend['spend']).round(2)- marketing_spend['roas']).sum()

np.float64(0.0)

In [16]:
platform_marketing = marketing_spend.groupby('platform').agg(total_revenue =('revenue_attributed','sum'),
                                                            total_spend = ('spend','sum'),
                                                            total_conversions = ('conversions','sum'),
                                                            total_clicks = ('clicks','sum' )).reset_index()

In [21]:
platform_marketing['roas'] = platform_marketing['total_revenue'] / platform_marketing['total_spend']
platform_marketing['spend_per_acquisisions'] = platform_marketing['total_spend'] / platform_marketing['total_conversions']
platform_marketing['spend_per_clicks'] = platform_marketing['total_spend'] / platform_marketing['total_clicks']
platform_marketing = platform_marketing.round(2)
platform_marketing.sort_values('total_revenue',ascending=False,inplace = True)
platform_marketing

,platform,total_revenue,total_spend,total_conversions,total_clicks,roas,spend_per_acquisisions,spend_per_clicks
3,Influencer,2216974.26,97663.12,28824,587501,22.70,3.39,0.17
2,Google Ads,2194120.83,152546.48,32309,611740,14.38,4.72,0.25
5,TikTok Ads,1374627.17,57229.22,18684,383269,24.02,3.06,0.15
1,Facebook Ads,1218572.43,106451.93,16968,331746,11.45,6.27,0.32
4,Instagram Ads,1024639.06,65154.02,13863,306843,15.73,4.70,0.21
0,Email Marketing,117681.45,24461.37,1370,25971,4.81,17.86,0.94

In [22]:
# Email Marketing is the worst performing

### 5. Recommendations

Create a one-page summary with your top 3 recommendations for improving profitability.

Reduce spend on low-ROAS platforms

Minimize return-related losses

Optimize shipping and discount costs